//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ученик.
    /// </summary>
    // *** Start programmer edit section *** (Ученик CustomAttributes)

    // *** End programmer edit section *** (Ученик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УченикE", new string[] {
            "Фио as \'Фио\'"})]
    [View("УченикL", new string[] {
            "Фио as \'Фио\'"})]
    public class Ученик : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        // *** Start programmer edit section *** (Ученик CustomMembers)

        // *** End programmer edit section *** (Ученик CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Фио CustomAttributes)

        // *** End programmer edit section *** (Ученик.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Фио Get start)

                // *** End programmer edit section *** (Ученик.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (Ученик.Фио Get end)

                // *** End programmer edit section *** (Ученик.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Фио Set start)

                // *** End programmer edit section *** (Ученик.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (Ученик.Фио Set end)

                // *** End programmer edit section *** (Ученик.Фио Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УченикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикE", typeof(IIS.Gostinica1.Ученик));
                }
            }
            
            /// <summary>
            /// "УченикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикL", typeof(IIS.Gostinica1.Ученик));
                }
            }
        }
    }
}
